title = 'fengx blog'
baseURL = 'https://blog.ofengx.com/'
languageCode = "zh-cn"
theme = 'ananke'
resourceDir = "resources"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"

[pagination]
  pagerSize = 10

[languages]
  [languages.zh]
    title = "fengx 博客"
    weight = 1
    contentDir = "content/zh"
  [languages.en]
    title = "fengx blog"
    weight = 2
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "feng xiang"
  favicon = "images/favicon.png"
  site_logo = "images/logo.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/heiyexinghai"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/efengx"
